//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQIDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMSBatchControlLog
    {
        public int DMSBatchControlLogID { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public string BatchName { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<bool> HDSExtract { get; set; }
        public Nullable<System.DateTime> HDSExtractDate { get; set; }
        public Nullable<int> MinPropertyId { get; set; }
        public Nullable<int> MaxPropertyId { get; set; }
        public Nullable<bool> SynchProject { get; set; }
        public Nullable<bool> SynchSharePoint { get; set; }
        public Nullable<bool> SynchMDS { get; set; }
        public Nullable<bool> SynchHDS { get; set; }
        public Nullable<System.DateTime> SynchProjectDateTime { get; set; }
        public Nullable<System.DateTime> SynchSharePointDateTime { get; set; }
        public Nullable<System.DateTime> SynchMDSDateTime { get; set; }
        public Nullable<System.DateTime> SynchHDSDateTime { get; set; }
        public string MSProjLocation { get; set; }
    }
}
