//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQIDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DQIEntities : DbContext
    {
        public DQIEntities()
            : base("name=DQIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DMSBatchControlLog> DMSBatchControlLogs { get; set; }
        public virtual DbSet<Grh_Assignments> Grh_Assignments { get; set; }
        public virtual DbSet<Grh_Tasks> Grh_Tasks { get; set; }
        public virtual DbSet<PRJ_Assignment_Table> PRJ_Assignment_Table { get; set; }
        public virtual DbSet<Resource_Table> Resource_Table { get; set; }
        public virtual DbSet<PRj_TaskTemplate> PRj_TaskTemplate { get; set; }
    }
}
