//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQIDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grh_Tasks
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string ResourceNames { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> Finish_Date { get; set; }
        public Nullable<int> OutlineLevel { get; set; }
        public Nullable<int> C__Complete { get; set; }
        public string Text21 { get; set; }
        public string Resource_Role { get; set; }
        public string IsAProperty { get; set; }
        public string FhFcPropertyID { get; set; }
        public string IsAFundSource { get; set; }
        public string OutlineNumber { get; set; }
        public string Note { get; set; }
    }
}
