//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQIDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grh_Assignments
    {
        public int ID { get; set; }
        public string Task_Name { get; set; }
        public string Resource_Name { get; set; }
        public string Percent_Work_Complete { get; set; }
        public Nullable<double> C__Complete { get; set; }
        public string Duration { get; set; }
        public string Actual_Work { get; set; }
        public string Scheduled_Work { get; set; }
        public Nullable<double> nActualWork { get; set; }
        public Nullable<double> nScheduled_Work { get; set; }
        public Nullable<double> nDuration { get; set; }
        public string xDuration { get; set; }
        public string xActual_work { get; set; }
        public string xSchedule_work { get; set; }
        public Nullable<System.DateTime> Finish_Date { get; set; }
    }
}
