//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQIDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRj_TaskTemplate
    {
        public int Taskid { get; set; }
        public Nullable<int> ID { get; set; }
        public string Active { get; set; }
        public string Task_Mode { get; set; }
        public string Name { get; set; }
        public string Duration { get; set; }
        public string Start { get; set; }
        public string Finish { get; set; }
        public string Predecessors { get; set; }
        public string Outline_Level { get; set; }
        public string Notes { get; set; }
        public string Resource_Name { get; set; }
        public string C__Work_Complete { get; set; }
        public string Work { get; set; }
        public string Units { get; set; }
        public string Work_Item_ID { get; set; }
        public string Area_Path { get; set; }
        public string Work_Item_Type { get; set; }
        public string Iteration_Path { get; set; }
        public string Publish_and_Refresh { get; set; }
        public string department { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> PrePred { get; set; }
        public Nullable<int> Batchid { get; set; }
    }
}
