//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQIDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRJ_Assignment_Table
    {
        public int id { get; set; }
        public string Task_Name { get; set; }
        public string Resource_Name { get; set; }
        public string C__Work_Complete { get; set; }
        public string Work { get; set; }
        public string Units { get; set; }
    }
}
