//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQIDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Table
    {
        public int Resource_tableID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Material_Label { get; set; }
        public string Initials { get; set; }
        public string Group_Name { get; set; }
        public string Max_Units { get; set; }
        public string Standard_Rate { get; set; }
        public string Overtime_Rate { get; set; }
        public string Cost_Per_Use { get; set; }
        public string Accrue_At { get; set; }
        public string Base_Calendar { get; set; }
        public string Department_Sequence { get; set; }
    }
}
